### ISSUE TITLE
Temporary file name not unique enough

### ISSUE THREAD

**Issue by crjones-amath** [E3SM-Project/HICCUP#11]
This problem manifests itself when multiple instances are initialized during the same second (e.g., when launching multiple processes in parallel). One solution that works is to use the `uuid` module to append a unique id to the temporary file names:

https://github.com/E3SM-Project/HICCUP/blob/4046a2598dcd4caa4f821d7085b526ab0902221f/hiccup/hiccup_data_class.py#L488

```
import uuid
...
    tmp_file_name += f'.{timestamp}.{uuid.uuid4().hex}'
```

**Comment by whannah1** [comment]
I'm closing this since it's an old issue, but also because there is an easy way to fix this problem now.

The current "best practice" is to use the "multifile" methods that break up each dataset into separate files for each variable. A dictionary is used to handle this, and the temporary file timestamp can be assigned when the dict is created

So if the user is creating many files in parallel, instead of letting `get_multifile_dict` create it's own timestamp based on the current time:
```
    file_dict = hiccup_data.get_multifile_dict(verbose=verbose)
```
We can now use the timestamp argument to set a unique timestamp for each set of temporary files. When building a hiccup script to cover a list of dates and times I recommend using the following appraoch: 
```
# specify the start and end date/time
bdate_str,edate_str = '2020-01-20 00','2020-01-26 21' 

# Create list of date and time 
beg_date = datetime.datetime.strptime(bdate_str, '%Y-%m-%d %H')
end_date = datetime.datetime.strptime(edate_str, '%Y-%m-%d %H')
datetime_list = pd.date_range(beg_date, end_date, freq='3H')

[...]

for t in datetime_list:

    curr_datetime = t.strftime("%Y-%m-%d-%H")
    
    src_atm_file = f'{src_data_root}/ERA5.atm.{curr_datetime}:00.nc'
    src_sfc_file = f'{src_data_root}/ERA5.sfc.{curr_datetime}:00.nc'
    
    output_atm_file_name = f'{dst_data_root}/HICCUP.nudging_uv_era5.{curr_datetime}.{dst_horz_grid}.{dst_vert_grid}.nc'
    
    hiccup_data = hdc.create_hiccup_data(...)
    
    file_dict = hiccup_data.get_multifile_dict(verbose=verbose ,timestamp=curr_datetime)
    
    [...]
```
The approach above was taken from an example meant to process multiple files in serial, but it could be adapted to launch batch system jobs in parallel. Also, if someone was creating multiple files for the same date, but perhaps different grids, then this appraoch would need to be modified to fit the situation.
